@echo off
echo Downloading ffmpeg...
powershell -Command "Invoke-WebRequest https://www.gyan.dev/ffmpeg/builds/ffmpeg-release-essentials.zip -OutFile ffmpeg.zip"
echo Extracting ffmpeg...
powershell -Command "Expand-Archive -Path .\ffmpeg.zip -DestinationPath .\ -Force"
echo Setting up environment variable...
setx /M PATH "%PATH%;%CD%\ffmpeg\bin"
echo Done!
